### ISSUE TITLE
Test pypi-deployed version

### ISSUE THREAD

**Issue by magland** [flatironinstitute/hither#48]
From a fresh environment (ideally docker isolation), pip install hither and then run a test of some kind.

Question: can we run the unit tests from deployed version? @jsoules, can you look into this? Maybe pytest has a way to do this.

**Comment by magland** [comment]
As we discussed:
(a) add the tests directory to the package bundle (use MANIFEST.in approach)
(b) make a bin/hither-test script that calls pytest with the correct working directory and arguments

**Comment by jsoules** [comment]
I think at this point the only barrier is actually pushing the code to PyPI and rerunning tests with installation straight from the remote repository. Otherwise this is resolved. Your call whether to close now, push another pre-release version and test that, or leave this open as a reminder for when we're ready to release.

**Comment by magland** [comment]
@jsoules, this is great.

I just committed a test of the deployed package using docker.

```
cd devel/test_deployed
./build_and_run_test.sh
```

It worked for me, so I'm going to make a PR -- and we can mark this issue as closed.
